SELECT *
FROM DW_SCHEMA.MV_TIME_TRIP
FETCH FIRST 10 ROWS ONLY;

SELECT *
FROM DW_SCHEMA.MV_STATION_TRIP
ORDER BY trip_count_by_start DESC
FETCH FIRST 10 ROWS ONLY;

SELECT * 
FROM DW_SCHEMA.MV_STATION_ROUTE
ORDER BY trip_count DESC
FETCH FIRST 10 ROWS ONLY;

SELECT *
FROM DW_SCHEMA.MV_BIKE_TRIP_DURATION
ORDER BY trip_count DESC
FETCH FIRST 10 ROWS ONLY;

SELECT *
FROM DW_SCHEMA.MV_USER_SEGMENTATION
WHERE ROWNUM < 10;
