# docker compose for development Windows OS
name: toronto-shared-bike

services:
  oracle19cDB-dev:
    container_name: oracle19cDB-dev
    restart: unless-stopped
    image: simonangelfong/oracledb19c:1.0
    env_file:
      - ./env/orcl.env
    volumes:
      - ./scripts/setup:/opt/oracle/scripts/setup # script to run after setup
      - ./scripts:/project/scripts # scripts
      # dev
      - oracledata2:/opt/oracle/oradata # persist data
      # - testdata:/opt/oracle/oradata # test data
      - ../project/orabackup:/opt/oracle/fast_recovery_area # backup
      - ../project/source:/project/source # source data
      - ../project/dpump:/project/dpump # export and import data
    networks:
      - private-net # Private network for prod
      - public-net # public for dev
    ports:
      - 1521:1521
    healthcheck:
      test: ["CMD-SHELL", "/project/scripts/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 2m

volumes:
  # oracledata:
  oracledata2:
  # testdata:

networks:
  public-net:
    driver: bridge
  private-net:
    driver: bridge
    internal: true
