# docker compose for development Windows OS
name: toronto-shared-bike

services:
  oracle19cDB:
    container_name: oracle19cDB
    # restart: unless-stopped
    image: simonangelfong/oracledb19c:1.0
    env_file:
      - /project/env/oracle19cDB.env
    # ulimits:
    #   nofile:
    #     soft: 65536
    #     hard: 65536
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2.0"
    #       memory: 8g
    #     reservations:
    #       memory: 4g
    volumes:
      - ./scripts/setup:/opt/oracle/scripts/setup # script to run after setup
      - ./scripts:/project/scripts # scripts
      # prod
      - /project/data:/project/data # source data
      - oracledata:/opt/oracle/oradata # persist data
      # - /project/oradata:/opt/oracle/oradata # local persist data
      - /project/orabackup:/project/orabackup # local backup data
      # - /project/remotebackup:/project/remotebackup # remote backup data
    networks:
      - private-net # Private network for prod
    ports:
      - 1521:1521
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'exit' | sqlplus -S sys/${ORACLE_PWD}@${ORACLE_SID} as sysdba",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5m

volumes:
  oracledata:

networks:
  private-net:
    driver: bridge
    internal: true

