# docker compose for development Windows OS
name: toronto-shared-bike

services:
  oracle19cDB:
    container_name: oracle19cDB
    restart: unless-stopped
    image: simonangelfong/oracledb19c:1.0
    env_file:
      - ./env/orcl.env
    volumes:
      - ./scripts/setup:/opt/oracle/scripts/setup # script to run after setup
      - ./scripts:/project/scripts # scripts
      # dev volumes
      - oracledata:/opt/oracle/oradata # persist data
      - ../project/data:/project/data # source data
      - ../project/orabackup:/project/orabackup # local backup
      # - ../project/nfsbackup:/project/nfsbackup # optional: remote backup
    networks:
      - private-net # Private network for prod
      # - public-net # public for dev
    ports:
      - 1521:1521
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-S",
          "sys/${ORACLE_PWD}@${ORACLE_SID}",
          "as",
          "sysdba",
          "<<<",
          "exit",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5m

volumes:
  oracledata:

networks:
  public-net:
    driver: bridge
  private-net:
    driver: bridge
    internal: true
