global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.100.100:8080']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']