name: toronto-shared-bike

include:
  - ../oracledb/compose.oracledb.dev.yaml

services:
  fastapi-app-dev:
    container_name: fastapi-app-dev
    restart: unless-stopped
    # image: simonangelfong/toronto-shared-bike-fastapi-prebuilt:v1.0 # using prebuild image
    build:
      context: ./app/
      dockerfile: Dockerfile
    env_file:
      - ./env/fastapi.dev.env
    ports:
      - "8080:8000"  # dev: expose localhost:8080
    networks:
      - public-net
      - private-net
    depends_on:
      - "oracle19cDB-dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  public-net:
    driver: bridge
  private-net:
    driver: bridge
    internal: true
