-- Set PDB context
ALTER SESSION SET CONTAINER = toronto_shared_bike;

-- drop existing objects
DROP INDEX DW_SCHEMA.idx_mv_time_trip_year_month;
DROP INDEX DW_SCHEMA.idx_mv_time_trip_year_hour;

DROP MATERIALIZED VIEW DW_SCHEMA.MV_TIME_TRIP;
DROP MATERIALIZED VIEW DW_SCHEMA.MV_STATION_TRIP;
DROP MATERIALIZED VIEW DW_SCHEMA.MV_STATION_ROUTE;
DROP MATERIALIZED VIEW DW_SCHEMA.MV_BIKE_TRIP_DURATION;
DROP MATERIALIZED VIEW DW_SCHEMA.MV_USER_SEGMENTATION;

DROP MATERIALIZED VIEW LOG ON DW_SCHEMA.fact_trip;
DROP MATERIALIZED VIEW LOG ON DW_SCHEMA.dim_time;
DROP MATERIALIZED VIEW LOG ON DW_SCHEMA.dim_station;

DROP TABLESPACE mv_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

