-- Create Dedicated schema in the PDB
SET SERVEROUTPUT ON;
set sqlblanklines on
ALTER SESSION SET CONTAINER = toronto_shared_bike;

-- Create the DW_SCHEMA user
CREATE USER DW_SCHEMA
IDENTIFIED BY "DwSchemaSecurePass123"
DEFAULT TABLESPACE FACT_TBSP
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON FACT_TBSP
QUOTA UNLIMITED ON DIM_TBSP
QUOTA UNLIMITED ON INDEX_TBSP
QUOTA UNLIMITED ON STAGING_TBSP;

-- Grant necessary privileges to DW_SCHEMA
--GRANT CREATE SESSION TO DW_SCHEMA;-- Allow login
GRANT CREATE TABLE TO DW_SCHEMA;

