SET SERVEROUTPUT ON;
ALTER SESSION SET CONTAINER=toronto_shared_bike;
show con_name
show user

-- Drop tbsp
DROP TABLESPACE FACT_TBSP
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE dim_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE index_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

DROP TABLESPACE staging_tbsp
INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

-- confirm
SELECT 
    tablespace_name
FROM DBA_tablespaces
WHERE tablespace_name LIKE '%_TBSP';
