---
- name: Configure autofs to mount NFS share at /project
  hosts: application_node
  become: true

  vars:
    nfs_server: 192.168.128.10
    export_path: /srv/project
    mount_point: /project
    autofs_map_dir: /etc/auto.master.d
    autofs_map_file: project.nfs

  tasks:
    - name: Install autofs
      package:
        name: autofs
        state: present

    - name: Create NFS mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Ensure entry in /etc/auto.master for direct map
      lineinfile:
        path: /etc/auto.master
        regexp: "^/-"
        line: "/-  {{ autofs_map_dir }}/{{ autofs_map_file }}"
        state: present

    - name: Ensure auto.master.d directory exists
      file:
        path: "{{ autofs_map_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create direct map file for /project
      copy:
        dest: "{{ autofs_map_dir }}/{{ autofs_map_file }}"
        content: |
          {{ mount_point }} {{ nfs_server }}:{{ export_path }}
        owner: root
        group: root
        mode: '0644'

    - name: Reload autofs service
      service:
        name: autofs
        state: reloaded
        enabled: true

    - name: Restart autofs service
      service:
        name: autofs
        state: restarted
        enabled: true

    - name: Verify mount by accessing directory
      command: ls -l {{ mount_point }}
      register: mount_output
      changed_when: false

    - name: Show mounted directory contents
      debug:
        var: mount_output.stdout_lines
