name: toronto-shared-bike

include:
  - ../fastapi/compose.fastapi.dev.yaml

services:
  nginx-proxy-dev:
    container_name: nginx-proxy-dev
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./config/nginx.dev.conf:/etc/nginx/nginx.conf:ro # Mount Nginx config
    networks:
      - public-net
    ports:
      - "8000:8000"
    depends_on:
      - "fastapi-app-dev"

networks:
  public-net:
    driver: bridge
  private-net:
    driver: bridge
    internal: true
