-- script to refresh MV
SET SERVEROUTPUT ON;
ALTER SESSION SET CONTAINER = toronto_shared_bike;

EXEC DBMS_MVIEW.REFRESH('DW_SCHEMA.MV_TIME_TRIP', 'F');
EXEC DBMS_MVIEW.REFRESH('DW_SCHEMA.MV_STATION_TRIP', 'C');
EXEC DBMS_MVIEW.REFRESH('DW_SCHEMA.MV_STATION_ROUTE', 'F');
EXEC DBMS_MVIEW.REFRESH('DW_SCHEMA.MV_BIKE_TRIP_DURATION', 'C');
EXEC DBMS_MVIEW.REFRESH('DW_SCHEMA.MV_USER_SEGMENTATION', 'C');

