pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                // Give execute permission and run the script
                sh 'chmod +x devops/shell/01_install_docker.sh'
                sh './devops/shell/01_install_docker.sh'
            }
        }
    }
}
