name: toronto-shared-bike

include:
  - ../nginx/compose.nginx.dev.yaml

services:
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    env_file:
      - ./env/cloudflare.env
    command: tunnel run
    networks:
      - public-net
    depends_on:
      - nginx-proxy

networks:
  public-net:
    driver: bridge
  private-net:
    driver: bridge
    internal: true
