name: Deploy to S3

on:
  push:
    branches: [ feature-devops ]  
  workflow_dispatch:    # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1  
        
    - name: Deploy to S3
      run: |
        aws s3 cp s3/ s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive